import {useState} from 'react';
import {api} from './api';
import ResourceCard from './ResourceCard';
import type {Report} from './types';

export default function ClinicalPanel({report,onUpdate}:{report:Report;onUpdate:(r:Report)=>void}) {
 const [text,setText]=useState(report.discharge?.text||''),[verified,setVerified]=useState(report.discharge?.status==='verified_by_user');
 const [topic,setTopic]=useState(report.web_resources?.topic||''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const run=async(path:string,body:unknown)=>{setBusy(true);setError('');try{onUpdate(await api<Report>(`/api/studies/${report.study_id}/${path}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}));}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 return <>{error&&<p className="error" role="alert">{error}</p>}<section className="card"><h2>Медицинская выписка</h2><p className="caption">Фото хранится локально. Проверьте распознанный текст перед интерпретацией.</p>{report.discharge&&<>{report.discharge.photo_attached&&<a href={`/api/studies/${report.study_id}/files/discharge_photo`} target="_blank" rel="noreferrer">Открыть прикреплённое фото</a>}{report.discharge.warning&&<p role="status">{report.discharge.warning}</p>}</>}<label className="field-label" htmlFor="discharge-review">Текст выписки</label><textarea id="discharge-review" rows={7} maxLength={30000} value={text} disabled={busy} onChange={e=>{setText(e.target.value);setVerified(false);}}/><label><input type="checkbox" checked={verified} disabled={busy} onChange={e=>setVerified(e.target.checked)}/> Текст сверен с оригиналом</label><div className="actions"><button className="secondary" disabled={busy} onClick={()=>run('discharge',{text,verified})}>Сохранить и обновить гипотезы</button></div></section>
 <section className="card"><h2>Предварительная диагностическая оценка</h2><p><strong>Диагноз из анкеты / документов:</strong> {report.clinical_review?.documented_diagnosis||'Не указан в анкете — проверьте текст выписки выше'}</p>{report.clinical_review?.hypotheses.map((h,i)=><article className="clinical-hypothesis" key={i}><h3>{h.title}</h3><p><strong>Основания:</strong> {h.basis.join('; ')}</p><p><strong>Альтернативы:</strong> {h.alternatives.join('; ')}</p><p><strong>Как проверить:</strong> {h.checks.join('; ')}</p></article>)}<p className="caption">{report.clinical_review?.note||'Это сохранённое исследование предыдущей версии. Для оценки выбранных областей выберите их на схеме рядом с видео.'}</p></section>
 <section className="card"><h2>Лечение и восстановление: материалы из интернета</h2><label className="field-label" htmlFor="web-topic">Общий диагноз или тема поиска</label><input id="web-topic" value={topic} maxLength={160} disabled={busy} placeholder="Например: реабилитация после инсульта" onChange={e=>setTopic(e.target.value)}/><p className="caption">В поисковик отправляется только эта строка. Не вводите ФИО и другие персональные сведения. Фото, видео и текст выписки не отправляются.</p><button className="primary" disabled={busy||topic.trim().length<2} onClick={()=>run('resources',{topic})}>{busy?'Обработка…':'Найти рекомендации, ЛФК и примеры восстановления'}</button>{report.web_resources&&<><p className="caption">{report.web_resources.note}</p><p>Поиск: {new Date(report.web_resources.generated_at).toLocaleString('ru-RU')}</p>{report.web_resources.warnings.map(w=><p key={w} className="caption">{w}</p>)}<div className="resources-grid">{report.web_resources.groups.map(g=><article key={g.id}><h3>{g.title}</h3><p className="caption">{g.status==='completed'?'Найдены материалы по теме реабилитации':g.status==='no_relevant_results'?'Подходящих материалов не найдено':g.status==='no_results'?'Результатов нет':'Автоматический поиск недоступен'}</p><div className="resource-list">{g.sources.map(s=><ResourceCard key={s.url} source={s}/>)}</div><a href={g.search_url} target="_blank" rel="noreferrer">Открыть этот запрос в поисковике ↗</a></article>)}</div></>}</section></>;
}
