import { useState } from 'react';
import { BookOpen, ShieldCheck, Search, LoaderCircle, RefreshCw, ExternalLink } from 'lucide-react';
import { api } from './api';
import type { Report, EvidenceSource, FeatureLink } from './types';

const topicNames: Record<string,string> = {upper_limb:'Верхняя конечность',shoulder_movement:'Движение плеча',elbow_extension:'Разгибание локтя',reaching:'Достижение цели рукой',trunk_control:'Контроль туловища',occupational_therapy:'Эрготерапия и ADL',bilateral_training:'Двусторонняя практика',mirror_therapy:'Зеркальная терапия',cimt:'CIMT',electrical_stimulation:'Электростимуляция',task_practice:'Функциональная практика'};
const typeNames: Record<string,string> = {clinical_practice_guideline:'Клинические рекомендации',systematic_review:'Систематический обзор',meta_analysis:'Метаанализ',randomized_controlled_trial:'Рандомизированное исследование',observational_study:'Наблюдательное исследование',other:'Другой тип публикации'};
const categories: Record<string,string> = {therapeutic_exercise:'ЛФК / therapeutic exercise',physiotherapy:'Физиотерапия',occupational_therapy:'Эрготерапия'};
const metricNames: Record<string,string> = {shoulder_max:'Максимальный угол плеча',elbow_max:'Максимальный угол локтя',wrist_mean_speed:'Средняя скорость кисти',max_lateral_tilt_change:'Изменение наклона корпуса'};
const units: Record<string,string> = {deg:'°','shoulder_width/s':'ШП/с'};

function Citations({sources}:{sources:EvidenceSource[]}) {
 return <div className="evidence-citations">{sources.map(s=><a key={s.id} href={s.url} target="_blank" rel="noreferrer">{s.authors_or_organization.startsWith('National Institute')?'NICE':s.authors_or_organization.startsWith('Intercollegiate')?'UK/Ireland':s.authors_or_organization.split(',')[0]} · {s.year}<ExternalLink size={11}/></a>)}</div>;
}
function Features({links}:{links:FeatureLink[]}) {
 return <details className="feature-links"><summary>Измерения, связанные с темой поиска</summary><ul>{links.map(link=>{const [group,key]=link.metric.split('.');return <li key={link.metric}>{group==='left_arm'?'Левая рука':group==='right_arm'?'Правая рука':'Корпус'} · {metricNames[key]??key}: {link.value.toFixed(2)} {units[link.unit]??link.unit} · надёжность {link.technical_reliability==='high'?'высокая':'средняя'}</li>;})}</ul><p>Связь тематическая. Эти значения не подтверждают слабость, заболевание или показания к лечению.</p></details>;
}
function Source({source:s}:{source:EvidenceSource}) {
 return <article className="evidence-source"><div className="source-top"><span className="tag">{typeNames[s.publication_type]??s.publication_type} · {s.year}</span><small>{s.verification_scope==='reviewed_content'?'Содержание проверено':'Проверена библиография'}</small></div><a className="source-title" href={s.url} target="_blank" rel="noreferrer">{s.title} <ExternalLink size={13}/></a><p className="source-authors">{s.authors_or_organization}</p><p>{s.summary}</p><div className="strength">{s.evidence_strength}</div>{s.locator&&<small>{s.locator}</small>}<div className="source-meta"><span>Дата проверки: {s.accessed_at.slice(0,10)}</span>{s.doi&&<span>DOI: {s.doi}</span>}</div></article>;
}

export default function EvidencePanel({report,onUpdate}:{report:Report;onUpdate:(report:Report)=>void}) {
 const [topic,setTopic]=useState('upper_limb'),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const bundle=report.evidence;
 const refresh=async(online:boolean,requestedTopic?:string)=>{
   setBusy(true);setError('');
   try {onUpdate(await api<Report>(`/api/studies/${report.study_id}/evidence`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({online,topic:online?(requestedTopic??topic):null})}));}
   catch(e){setError((e as Error).message);}finally{setBusy(false);}
 };
 const available=(bundle?.topics??[]).filter(t=>t!=='task_practice');
 const selectedTopic=available.includes(topic)?topic:available[0]??'';
 return <div className="evidence-panel">
   <section className="card"><div className="panel-heading"><h2><BookOpen size={20}/> Медицинская литература и контекст</h2><span className="tag">Отдельно от измерений</span></div><p className="evidence-intro">Наблюдения на видео помогают выбрать тему литературы. Применимость методов к пациенту требует оценки специалистом: это не диагноз и не индивидуальное назначение.</p>
     {!bundle?<><p>В этом сохранённом отчёте ещё нет Evidence Service. Можно добавить контекст без повторного анализа видео.</p><button className="secondary" disabled={busy} onClick={()=>refresh(false)}><RefreshCw size={15}/> Добавить проверенные источники</button></>:<>
       <div className="catalog-summary"><span>Каталог {bundle.catalog_version}</span><span>{bundle.sources.length} проверенных источников</span><button className="secondary" disabled={busy} onClick={()=>refresh(false)}><RefreshCw size={13}/> Обновить подбор</button></div>
       <p className="caption">{bundle.selection_note}</p>
       {(report.clinical_context??[]).map(context=><article className="clinical-context" key={context.id}><p>{context.statement}</p><div className="strength">Характер доказательств: {context.evidence_strength}</div><Citations sources={context.evidence}/><Features links={context.feature_links}/><small>{context.confidence}</small></article>)}
       {!(report.clinical_context??[]).length&&<p className="no-evidence">Нет надёжных измерений или доступных проверенных доказательств для формирования контекста. Отсутствующие данные не заменяются гипотезами.</p>}
       {!!report.evidence_disagreements?.length&&<div className="literature-differences"><h3>Различия рекомендаций и неопределённость</h3>{report.evidence_disagreements.map(d=><article key={d.topic}><strong>{d.topic}</strong><p>{d.statement}</p><Citations sources={d.evidence}/></article>)}</div>}
     </>}
   </section>
   <section className="safety before-rehab"><ShieldCheck size={26}/><div><h3>{report.safety_screen?.title??'Безопасность перед обсуждением реабилитации'}</h3><p>{report.safety_screen?.statement??report.safety}</p><div className="safety-checks">{report.safety_screen?.video_cannot_assess.map(x=><span key={x}>{x}</span>)}</div><p><strong>{report.safety_screen?.individual_plan??'Индивидуальный план должен утверждаться медицинским специалистом.'}</strong></p><p>{report.safety_screen?.not_prescribed}</p></div></section>
   <section className="card"><div className="panel-heading"><h2>Возможные направления реабилитации</h2><span className="tag">Для обсуждения со специалистом</span></div><p className="evidence-intro">Подбор отражает тематику измерений. Показания, противопоказания и пригодность каждого метода по этому видео не определены.</p>{Object.entries(categories).map(([key,label])=>{const options=(report.rehabilitation_options??[]).filter(o=>o.category===key);return options.length?<div className="rehab-category" key={key}><h3>{label}</h3>{options.map(o=><article className="rehab-option" key={o.id}><h4>{o.option}</h4><p className="strength">{o.evidence_strength}</p><p>{o.clinician_checks}</p><Features links={o.feature_links}/><Citations sources={o.evidence}/><small className="review-required">{o.disclaimer}</small></article>)}</div>:null;})}{!(report.rehabilitation_options??[]).length&&<p>Направления не сформированы: недостаточно надёжных данных или проверенных источников.</p>}</section>
   {bundle&&<section className="card"><div className="panel-heading"><h2>Источники и поиск актуальных публикаций</h2><a className="secondary" href={`/api/studies/${report.study_id}/files/evidence`} download>Экспорт Evidence JSON</a></div><details className="sources-list"><summary>Проверенные источники · {bundle.sources.length}</summary>{bundle.sources.map(source=><Source key={source.id} source={source}/>)}</details><div className="pubmed-search"><h3>Дополнительный поиск PubMed</h3><p>В NCBI отправляется только общий запрос по выбранной теме. Видео, значения метрик, сторона поражения, задание и идентификатор исследования не отправляются.</p><div className="search-controls"><select aria-label="Тема медицинской литературы" value={selectedTopic} onChange={e=>setTopic(e.target.value)} disabled={busy||!available.length}>{available.map(t=><option key={t} value={t}>{topicNames[t]??t}</option>)}</select><button className="primary" disabled={busy||!available.length} onClick={()=>{setTopic(selectedTopic);setBusy(true);setError('');api<Report>(`/api/studies/${report.study_id}/evidence`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({online:true,topic:selectedTopic})}).then(onUpdate).catch(e=>setError(e.message)).finally(()=>setBusy(false));}}>{busy?<LoaderCircle size={16} className="spin"/>:<Search size={16}/>} Найти в PubMed</button></div><p className="caption">Последние 5 лет · приоритет рекомендаций и обзоров · до 5 результатов за запрос. Библиографическая проверка не заменяет оценку содержания: результаты поиска не добавляются автоматически к рекомендациям.</p>{bundle.online_search.status==='completed'&&<p className="search-status">Поиск выполнен · {bundle.online_search.accessed_at?.slice(0,10)}{bundle.online_search.from_cache?' · кэш до 24 ч':''}. Найдено пригодных записей: {bundle.search_results.length}.</p>}{bundle.online_search.query&&<details><summary>Поисковый запрос</summary><code className="query-text">{bundle.online_search.query}</code></details>}{bundle.warnings.map(w=><p className="error" key={w}>{w}</p>)}{bundle.search_results.map(source=><Source key={source.id} source={source}/>)}</div></section>}
   {error&&<p className="error" role="alert">{error}</p>}
 </div>;
}
